# Generated by Django 4.1.7 on 2023-03-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, unique=True)),
                ('apellidos', models.CharField(max_length=255, unique=True)),
                ('dni', models.IntegerField(max_length=9, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
