# Generated by Django 4.1.7 on 2023-03-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureza', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSulfuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sulfuro', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField()),
                ('cod_asignado', models.CharField(max_length=2, unique=True)),
                ('kg_estimados', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('guia_recepcion', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('dureza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.materialdureza')),
                ('humedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.materialhumedad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.origenmaterial')),
                ('sulfuro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.materialsulfuro')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='molienda.materialtamaño')),
            ],
        ),
    ]
